default_agent: atomicLime_Agent
is_agentcore_create_with_iac: true
agents:
  atomicLime_Agent:
    name: atomicLime_Agent
    entrypoint: /Users/katherinehummel/git/agentcore-runtime-quickstart/atomicLime/src/main.py
    deployment_type: container
    source_path: /Users/katherinehummel/git/agentcore-runtime-quickstart/atomicLime/src
    aws:
      account: null
      region: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    is_generated_by_agentcore_create: true
